simulados = {
    "Colmeias_Inicial": {
        "Gabarito": {
            "1": {"Resposta": "D", "Disciplina": "Português", "Conteudo": ["Funções da Linguagem", "Morfologia"]},
            "2": {"Resposta": "A", "Disciplina": "Português", "Conteudo": ["Morfologia", "Concordância Verbal"]},
            "3": {"Resposta": "A", "Disciplina": "Português", "Conteudo": ["Funções da Linguagem", "Variação Linguística"]},
            "4": {"Resposta": "C", "Disciplina": "Português", "Conteudo": ["Figuras de Linguagem", "Morfologia", "Verbos"]},
            "5": {"Resposta": "E", "Disciplina": "Português", "Conteudo": ["Morfologia", "Substantivo, Adjetivo, Numeral e Artigo"]},
            "6": {"Resposta": "D", "Disciplina": "Física", "Conteudo": ["Movimento uniforme", "Matemática Básica", "Porcentagem"]},
            "7": {"Resposta": "B", "Disciplina": "Física", "Conteudo": ["Ondulatória", "Movimento Uniforme"]},
            "8": {"Resposta": "E", "Disciplina": "Física", "Conteudo": ["Eletricidade", "Gráficos"]},
            "9": {"Resposta": "E", "Disciplina": "Matemática", "Conteudo": ["Geometria Espacial", "Volume"]},
            "10": {"Resposta": "A", "Disciplina": "Matemática", "Conteudo": ["Medidas de Centralidade e Dispersão", "Tabela"]},
            "11": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Matemática Básica", "Adição e Subtração", "Potenciação", "Radiciação"]},
            "12": {"Resposta": "B", "Disciplina": "Matemática", "Conteudo": ["Porcentagem", "Matemática Financeira"]},
            "13": {"Resposta": "C", "Disciplina": "Matemática", "Conteudo": ["Função do 1º Grau", "Gráficos", "Tabela"]},
            "14": {"Resposta": "B", "Disciplina": "Geografia", "Conteudo": ["Conceitos em Geografia e Introdução à Demografia", "Migrações"]},
            "15": {"Resposta": "E", "Disciplina": "Geografia", "Conteudo": ["Industrialização Brasileira"]},
            "16": {"Resposta": "C", "Disciplina": "Geografia", "Conteudo": ["Energia"]},
            "17": {"Resposta": "C", "Disciplina": "História", "Conteudo": ["Governo Vargas"]},
            "18": {"Resposta": "B", "Disciplina": "História", "Conteudo": ["Idade Moderna"]},
            "19": {"Resposta": "B", "Disciplina": "História", "Conteudo": ["Segunda Guerra Mundial", "Autoritarismo"]},
            "20": {"Resposta": "A", "Disciplina": "Química", "Conteudo": ["Química Orgânica"]},
            "21": {"Resposta": "A", "Disciplina": "Química", "Conteudo": ["Química Orgânica", "Classificação e Hibridização do Carbono", "Classificação de Cadeias Carbônicas"]},
            "22": {"Resposta": "D", "Disciplina": "Química", "Conteudo": ["Equilíbrio Iônico"]},
            "23": {"Resposta": "D", "Disciplina": "Biologia", "Conteudo": ["Biociclos e Biomas", "Ecologia"]},
            "24": {"Resposta": "C", "Disciplina": "Biologia", "Conteudo": ["Saúde"]},
            "25": {"Resposta": "D", "Disciplina": "Biologia", "Conteudo": ["Citologia"]}
        },
        "Gabaritos_Alunos": {
            "-NrBuWfRVnTXIqUkVD7j": "DADDCCBBDCBCBBECAAAABACCB",
            "-NpPiXstkQhpVUwXk02x": "BCCBBADCDEBCBCCADBBCDCBCE",
            "-NsZ2TUAS2FTuOMqw89H": "DADCBDBEEABBCBECABBAABCCD",
            "-NruBjdIiUYUWW5ABguL": "DACACBCDEDBBCCEAAEBABCADD",
            "-NsmN1MHlB1w7GpLDQ-U": "DBCCBCDCDBBABDACEDDABCDDD",
            "-Ns_3c3m8k479xbwz92A": "DAECBECEAABACAECCBDBEBCCD",
            "-Ns8MzOoubwwCWpPoAlD": "DDEDDCEECBBACBECBDBAADDDA",
            "-NrerG7lApyhE37b23Bq": "DAACBBAEBABAEDCAEECACACDD",
            "-NrtvOAF3cJtvYFfsGzC": "DAADDECDBABDCCAECADCBEACA",
            "-NsOPDxVBhcxUnh9B-sR": "DCCCEBECABBCCABCDBBACECDD",
            "-NtX17mTXwY95dYVHZ8U": "BAEBDCBEEADDCDECABBDBCDDE",
            "-NpWcFSP1y7uAO3gQO7U": "DABBCBDEEABBAAECDBBAACCCD",
            "-Ns8sq9Y9TPEtJqooBS6": "EECCABBECBBADACDECAAEBBAD",
            "-NsnzcJn11H_CFbx-EmB": "DDACEEDCCABBEAECBBBABBDDD",
            "-Ns8WSUNgdvUFcds4Z54": "DACCECCEBEBADABCEBBAAADED",
            "-Ns9eSl96YVtghzvsAwD": "ABEDBCCDADDACABCBEBADBCDD",
            "-NsY6FAnM58MtuZbY5hu": "DABDBCCCDEBAAABCCBCBBAEDC",
            "-Nq2cAnk4ZFdNbiTXe79": "DABBACDDBBBAEDECDBBAADCCD",
            "-NswaxcU1dM9Mi3FKZHK": "DABDCCBECEAECACDABDCBADCD",
            "-NsmHzt00jL-Jlmah01W": "DACDEBDCBDBBDCABEEDBFFFFF",
            "-Nt1TjePJxmLayK2xFmX": "DBADECBCDEADADCCBBDAAECCA",
            "-NpWLdJkscUyYXH143pn": "DBCCEEDEBABACEBCBECAAADDB",
            "-NpKGYe49ixF4BXth9dG": "DEDDCCAEBABDCABBCBCABCCCA",
            "-NrpsYAA3XldX1MQDHpT": "DCCADADEDABACAACBBAACBDED",
            "-NsmJ-pYkvkhcTRCTkTQ": "BCCBFCFCCFBDFDECCFFFFFFFF",
            "-Npu365YyDNGcTeR7fh-": "DECCEADECEBDACECABBABAACD",
            "-NpzrRxO6aaaWyn-osTm": "DCBDECAEDDBAAAECCDCABDDCC",
            "-NsUCHyhCYuW4frHavih": "DCDCEACEDBBBEBECDBBACCDEA",
            "-NpPaHEgFS-MtM6eoWrD": "DCACCABECBBACCECEBBACDDED",
            "-NpM60kZr97ETBSjT3em": "DBDCEDBEAABBCBBCEBBAADDDD",
            "-NsT3untPBVbLsxZMVHS": "DCADCEAECBBAABBCBBAAABDCD",
            "-Ns8r6VDAMD6IP95qS-s": "DDDCCCDEBCBAAAECCBBBEDDDA",
            "-NsTzS33TAhT_zgyRkN8": "DEDBDBDCBDBAAACCBBAAADCED",
            "-NpW7mAoNirVgqwj_OTh": "DACDECBCDCBCABBEEBBADAEDA",
            "-NsTs2dq4GFs_VpMQOij": "DAEBDCDECDBDAAECABCAADCED",
            "-NpUjYTOwJvPPxq_5tYE": "DADDDCCCBEBDCABCADCABCDCD",
            "-NsZ7IEQYxO9-cGpPG8f": "DEDDBEFBCEBDBABDDBBAACDCD",
            "-Nr0WkuCMbD90mu6mY_T": "DDBDCACABCBBABBCCDBACADDA",
            "-Nrq6lwAfkLPXeOQxPfz": "DCCDDDCEDABECAECEDCABADDD",
            "-Nr7ChLzI5WL-DXmRmvB": "DCBCEDEEDABBDDECABBAABDCD",   
            "-NpVOvNM5kPRN92UoiTe": "DAACECFEFDBBCBECCBBABADED",
            "-NrvCegRD76rYG-XsLoJ": "DACBBCACEEDCACDBAADACBDAA",
            "-NsYFspxJEiTiDW5hjsK": "BAECDBECBCDACACEBCDCABDCA",
            "-NsZT88aMZPMQg-is5AE": "CBCCCDDECADACABCEECABDCCA",
            "-NsJcmposNNkMqxQOpW-": "BABDABDDCABEDBCCCDACCBCCA",
            "-Nq2bedGQROrqUVWYy0s": "CABDAEECBABACADBCAAAADCBD",
            "-Nu-qsnPbBaEBagrevvV": "DBDBEDCEEABABCABEDACBBCEC",
            "-NtqIK4ame820uCcEAL0": "EBCCBBBDCBAEACCBEEDABBCCE",
            "-NsJziCuug-NS9grwFjW": "DAFCCDCEBABDBDCCABBABACDD",
            "-NrzK06W8HlJCHgnqfsc": "DADCEDCEEABBCABCEBBAADDCD",
            "-Npze7iSYGXgq6mSvsxw": "DAECDEEECBBDAEECBEAADBDED",
            "-Nr1Q5rL4YdJ4ePbJWUP": "DACBDDACBDBABBECDBBABBDED",
            "-Npe6HG4lBqyBdqxx2Hh": "DADCDDEDECBBCBECBEBACCDDD",
            "-NsPZD8J76PbJfhN8VHy": "DCBCDEDCBBBABBCCDBBADADCD",
            "-NsjGmbHx0mg3dng_t-U": "DEAAACCCCCBDBDECABBAABCED",
            "-NrGp70JkzBpzsDCJilf": "BCCCDCDECBDCAADCDBCBDACDD",
            "-NsZSxQiOeUmSXBcjA8s": "DCABAACEBABEBCCDBBCAABDEA",
            "-NqnKXr8J1VzCE_0HnhN": "DCBCECDEBDBADBBCDACDCBDCD",
            "-NpLmgvmQ2irtNwS5IJl": "ACCBBCEECEBADDECAACABDDCD",
            "-NsntqldomSiAanR3tyG": "DADCEEABCAAACACBDDBABADCD",
            "-NpK4z0EODLTECxOJzoO": "DAACEDDEBABCCABCCBBABBDDD",
            "-NpR3HewtcJrMyfKoFxb": "DCDBADDDDEBCAACAAADACCCED",
            "-NsYLDxPypTPNiNOpVr_": "AADDDDCDCABACCDCCBBEEBEEE",
            "-NsEdBrDl21dtr1r2Oz_": "ECBAAEEBEEBCACECCDBBCCCBD",
            "-Nu0i3HZRkPgnWV3cTgj": "DDCCEDECBEDAACCCDBBBACDDD",
            "-NsPWcJjjVBcyGfew-_Y": "DCEDEADDCDBBDACCDABAAACCD",
            "-NsON4LSXfwibuQexwuu": "CEDDACACEABCCBCCEBCACACDA",
            "-Ntrd0Y8mZRrCXZWWCHf": "DBACBDEDEBCAAAACADABDACDA",
            "-NsV4Fj2QZqlNkwjWlhk": "DCDCDCCEDCADAAECADBAACDED",
            "-NsPMHwLvw51_vlTjU_v": "DABDDBCCECBCABCCBCADBACDD",
            "-NsPwDSC5zlU6xjLQkTE": "DAADECBECABDACBCABBAABDCD",
            "-NsKAfHzETpb6A29qUmE": "DCBDBECCCBBDAACBCEBACDCCD",
            "-Nsj8T2H5O2C_GGlnPT2": "DDBDCEACEAABCDBCBBBAABCDD",
            "-NpMM8woPq89N863HG2J": "DADCDABEDCBBAAECCBBAADDCD",
            "-Ntg2qm_mumKdE_HFBUZ": "ACBCCCDCDCBDBCCCAABABACCD",
            "-NsUAwL_5b_t4wJxmDHc": "DAADEECBBCBABDEEABDAABCCD",
            "-NpLsC8PSX2eIIISaP_v": "DAEDEBDCDABBEDECBBBCCADCD",
            "-NpLrGzNXMZeuOGz2tPV": "DBBCADCEEEBAAAEABCDCAACCD",
            "-NrzcUk2he0PVutmByQ6": "DEACEEDEBCBAABACCBBAADCCA",
            "-NpKJdnzEgtaWvMl2DUk": "DCBADCECDEAACDECEBBDDDFCA",
            "-NsIt72LxuiPGaK_ntrE": "DABDCACEEABABDEDAEBABACCA",
            "-NsIr2GBBkNl-K3J5PRS": "DACCCBACEECABAADCBBACADED",
            "-Nr_kRZEcbAXTP2qepsC": "DECCEDDBCBBAAABBEBBACBDCA",
            "-NrHNzZdQBcJE0qU7sI0": "DBDCBEEEDBBACAECADAAAADCD",
            "-Nrp-sxfD-5tC-L2Denn": "CCDCBAEECBBDAACCAACABAACD",
            "-NrClBYuWqNTs7y0jVYZ": "DCCDDEABCCBAADBCBCBBBACCD",
            "-NsKvR29sb7FxbqIpMH3": "ADEBCEAECBBAADBCDBCEDBCAA",
            "-NstwRhrlCZA0gA4o9Yu": "DCCCBCDBBDADEDBBEDBABCDAD",
            "-NrHzk1lVw-T3PooAfC_": "DDACDDBCEBBCCBECCBBAACCCD",
            "-NrI-b5fciAL2RlZpONZ": "DBABDBAEBCBCACECEBBCADCCD",
            "-NpVlanEWAtxkpH5sARU": "DECCBDDECBDBAABCCBBCCECDA",
            "-NsPshdnWzfiK_9cZlpE": "DCDDACBECABCDABCABBAABCCD",
            "-NsQ2P5CTw_EuPUn_z6F": "DCBDBCCBECDAABACCBBACADCD",
            "-NrbN5k7HtBLP23iJDcD": "DCECAEACDCBCCAAEDBCBABCAD",
            "-NqE5jQHQHQxYKHb2M9p": "DBDCCEEEDDBCADACCDBACCCCD",
            "-Nse2jIhaahBr-im3CiU": "DEEBEEDABEBBBDCCEDDCCBCAA",
            "-NqE7-yQQg8aavh-zZww": "DADDEECABDBAADBDEBBACBCDD",
            "-NrCT0dZcy_gtJ9HPYAN": "DADDCCDCEABEDAECBACAABDEC",
            "-NpPlHLIswZwfrP8Cncd": "DAEDBADECBDCBDECBDBABADCD",
            "-NrCq2JtQP0c0nEUtpml": "DADCEDCEDABBAAECDBCAADAED",
            "-Nq8DV6xcofQ6iln-mcc": "DCACEBCDCABBABECABBADBCCD",
            "-NsOv0lA47iH_NTQ0tKR": "DAEDEAEEEBDBCCEBBAAAADCCD",
            "-NsUYi1FaTFQvJgYArgI": "DDBEACBDEABACCACCDCAEACCA",
            "-NrgM6h9cr6spEw7eS5B": "DCCCDAECCDBDCDCDCDCABCCCD",
            "-NrQnDd70P_BVo86jErN": "DCDDEEEDDABCADECABCACDCCD",
            "-NrvdepIVDJ7xe6seuaz": "ACBBADCCCEDACABCEADABBCAD"
        }
    }
}